// Aztec.js integration hook for LinkedSpark

import { useState, useEffect, useCallback } from 'react';
import {
  createPXEClient,
  PXE,
  AccountWalletWithSecretKey,
  Fr,
  Contract,
  AztecAddress,
  getSchnorrAccount,
} from '@aztec/aztec.js';
import { hashLinkedInId } from '../utils/linkedin';

// Network configurations
const NETWORKS = {
  sandbox: 'http://localhost:8080',
  alpha: 'https://pxe.alpha.aztec.network', // Alpha mainnet PXE
} as const;

type NetworkName = keyof typeof NETWORKS;

interface UseAztecReturn {
  pxe: PXE | null;
  wallet: AccountWalletWithSecretKey | null;
  contract: Contract | null;
  isConnected: boolean;
  isLoading: boolean;
  error: string | null;
  connect: (network?: NetworkName) => Promise<void>;
  signalInterest: (myLinkedInId: string, theirLinkedInId: string) => Promise<string>;
  checkMutual: (myLinkedInId: string, theirLinkedInId: string) => Promise<boolean>;
  withdrawSignal: (theirLinkedInId: string) => Promise<boolean>;
  mySignals: Signal[];
  myMatches: Match[];
}

interface Signal {
  toLinkedInHash: string;
  stakeAmount: bigint;
  timestamp: number;
}

interface Match {
  theirLinkedInHash: string;
  matchedAt: number;
}

// Contract address (set after deployment)
const CONTRACT_ADDRESS = import.meta.env.VITE_CONTRACT_ADDRESS || '';

// Stake amount: $10 in USDC (6 decimals)
const STAKE_AMOUNT = BigInt(10_000_000);

export function useAztec(): UseAztecReturn {
  const [pxe, setPxe] = useState<PXE | null>(null);
  const [wallet, setWallet] = useState<AccountWalletWithSecretKey | null>(null);
  const [contract, setContract] = useState<Contract | null>(null);
  const [isConnected, setIsConnected] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [mySignals, setMySignals] = useState<Signal[]>([]);
  const [myMatches, setMyMatches] = useState<Match[]>([]);

  // Connect to Aztec network
  const connect = useCallback(async (network: NetworkName = 'sandbox') => {
    setIsLoading(true);
    setError(null);
    
    try {
      // Create PXE client
      const pxeUrl = NETWORKS[network];
      const pxeClient = createPXEClient(pxeUrl);
      setPxe(pxeClient);

      // Check if we have a stored secret key
      const storedKey = localStorage.getItem('linkedspark_secret_key');
      let secretKey: Fr;
      
      if (storedKey) {
        secretKey = Fr.fromString(storedKey);
      } else {
        // Generate new account
        secretKey = Fr.random();
        localStorage.setItem('linkedspark_secret_key', secretKey.toString());
      }

      // Create Schnorr account
      const account = getSchnorrAccount(pxeClient, secretKey, Fr.random());
      const walletInstance = await account.waitSetup();
      setWallet(walletInstance);

      // Load contract if address is set
      if (CONTRACT_ADDRESS) {
        // Import contract artifact (generated by codegen)
        const { OutOfOfficeContract } = await import('../artifacts/OutOfOffice');
        const contractInstance = await OutOfOfficeContract.at(
          AztecAddress.fromString(CONTRACT_ADDRESS),
          walletInstance
        );
        setContract(contractInstance);
      }

      setIsConnected(true);
    } catch (err) {
      console.error('Failed to connect:', err);
      setError(err instanceof Error ? err.message : 'Failed to connect to Aztec');
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Signal interest in someone
  const signalInterest = useCallback(
    async (myLinkedInId: string, theirLinkedInId: string): Promise<string> => {
      if (!contract || !wallet) {
        throw new Error('Not connected');
      }

      const myHash = hashLinkedInId(myLinkedInId);
      const theirHash = hashLinkedInId(theirLinkedInId);

      // Call the private function
      const tx = await contract.methods
        .signal_interest(myHash, theirHash, STAKE_AMOUNT)
        .send()
        .wait();

      // Update local state
      setMySignals(prev => [
        ...prev,
        {
          toLinkedInHash: theirHash.toString(),
          stakeAmount: STAKE_AMOUNT,
          timestamp: Date.now(),
        },
      ]);

      return tx.txHash.toString();
    },
    [contract, wallet]
  );

  // Check for mutual match
  const checkMutual = useCallback(
    async (myLinkedInId: string, theirLinkedInId: string): Promise<boolean> => {
      if (!contract || !wallet) {
        throw new Error('Not connected');
      }

      const myHash = hashLinkedInId(myLinkedInId);
      const theirHash = hashLinkedInId(theirLinkedInId);

      // Call the private function
      const result = await contract.methods
        .check_mutual(myHash, theirHash)
        .simulate();

      if (result) {
        // It's a match! Update local state
        setMyMatches(prev => [
          ...prev,
          {
            theirLinkedInHash: theirHash.toString(),
            matchedAt: Date.now(),
          },
        ]);
      }

      return result;
    },
    [contract, wallet]
  );

  // Withdraw a signal
  const withdrawSignal = useCallback(
    async (theirLinkedInId: string): Promise<boolean> => {
      if (!contract || !wallet) {
        throw new Error('Not connected');
      }

      const theirHash = hashLinkedInId(theirLinkedInId);

      const tx = await contract.methods
        .withdraw_signal(theirHash)
        .send()
        .wait();

      // Update local state
      setMySignals(prev =>
        prev.filter(s => s.toLinkedInHash !== theirHash.toString())
      );

      return true;
    },
    [contract, wallet]
  );

  return {
    pxe,
    wallet,
    contract,
    isConnected,
    isLoading,
    error,
    connect,
    signalInterest,
    checkMutual,
    withdrawSignal,
    mySignals,
    myMatches,
  };
}
